version: '3.8'
services:
    db:
      image: mysql:5.7
      ports:
        - '1234:3306'
      environment:
        MYSQL_DATABASE: 'new'
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_PASSWORD: 'password'
    app:
        build: . 
        volumes:
            - .:/django
        ports:
            - 8000:8000
        image: app:django
        container_name: dj_con
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - db
    