# Generated by Django 3.2.3 on 2021-05-25 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeadditional',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empsupervisor', to='base.supervisor'),
        ),
        migrations.AlterField(
            model_name='employeeadditional',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SupervisorAdditional',
        ),
    ]
